#!/usr/bin/env bash
# Emits the migrations from <first> onwards as one script for the Supabase SQL
# editor, for when nobody at the keyboard holds the CLI credentials that
# `supabase db push` needs (a login token and the database password).
#
# It concatenates the real migration files rather than restating their DDL, so
# the bundle cannot drift from `supabase/migrations/`. Every migration from 0013
# is written to be re-runnable, and the whole thing is wrapped in a transaction,
# so applying an already-applied migration is a no-op rather than a half-change.
#
#   ./supabase/migrations/bundle.sh 0013 > /tmp/pending.sql
#
# This does NOT write `supabase_migrations.schema_migrations`. That ledger is
# the CLI's, this project has never run the CLI against the hosted database, and
# a partial ledger would be worse than none: `db push` would then skip exactly
# the migrations it had no record of applying.
set -euo pipefail

first=${1:?usage: bundle.sh <first-migration-number, e.g. 0013>}
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

files=()
for f in "$dir"/[0-9][0-9][0-9][0-9]_*.sql; do
  [[ "$(basename "$f")" > "${first}_" || "$(basename "$f")" == "${first}_"* ]] && files+=("$f")
done

if [[ ${#files[@]} -eq 0 ]]; then
  echo "no migrations at or after ${first}" >&2
  exit 1
fi

echo "-- Generated by supabase/migrations/bundle.sh — do not edit, regenerate."
echo "-- Source of truth: supabase/migrations/"
printf -- '-- Contains: %s\n' "$(basename "${files[0]}")"
for f in "${files[@]:1}"; do printf -- '--           %s\n' "$(basename "$f")"; done
echo
echo "begin;"
echo
for f in "${files[@]}"; do
  echo "-- ==== $(basename "$f") ===================================="
  cat "$f"
  echo
done
echo "commit;"
